version: '3.8'

services:
  # Milvus 向量数据库
  milvus-standalone:
    image: milvusdb/milvus:v2.4.3
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - MINIO_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/milvus:/var/lib/milvus
    depends_on:
      - etcd
      - minio
    command: milvus run standalone
    networks:
      - ai-network
    restart: always

  # Milvus 依赖 - etcd
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./data/etcd:/etcd
    command:
      - etcd
      - -advertise-client-urls=http://etcd:2379
      - -listen-client-urls=http://0.0.0.0:2379
      - --data-dir=/etcd
    networks:
      - ai-network
    restart: always

  # Milvus 依赖 - MinIO (对象存储)
  minio:
    image: minio/minio:latest
    container_name: milvus-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - ai-network
    restart: always

  # MongoDB 文档数据库
  mongodb:
    image: mongo:6.0.18
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - ai-network
    restart: always

  # Neo4j 图数据库
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
    volumes:
      - ./data/neo4j:/data
    networks:
      - ai-network
    restart: always

  attu:
    image: zilliz/attu:v2.4.0
    container_name: attu
    ports:
      - "8000:3000"
    environment:
      MILVUS_URL: milvus-standalone:19530
    depends_on:
      - milvus-standalone
    networks:
      - ai-network
    restart: always

networks:
  ai-network:
    driver: bridge
    name: ai-network
